package quackie.gui;

import java.io.IOException;
import java.util.Collections;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.geometry.Pos;
import javafx.scene.Node;
import javafx.scene.control.Label;
import javafx.scene.layout.HBox;

/**
 * Displays one chat message together with an avatar identifying its author.
 */
public class DialogBox extends HBox {
    @FXML
    private Label dialog;

    @FXML
    private Label avatar;

    /**
     * Loads the dialog layout and fills it with a message.
     *
     * @param message message to display
     */
    private DialogBox(String message) {
        FXMLLoader fxmlLoader = new FXMLLoader(DialogBox.class.getResource("/view/DialogBox.fxml"));
        fxmlLoader.setController(this);
        fxmlLoader.setRoot(this);

        try {
            fxmlLoader.load();
        } catch (IOException exception) {
            throw new AssertionError("DialogBox FXML could not be loaded", exception);
        }

        dialog.setText(message);
    }

    /**
     * Creates a right-aligned dialog for a user command.
     *
     * @param message command entered by the user
     * @return user dialog box
     */
    public static DialogBox getUserDialog(String message) {
        DialogBox dialogBox = new DialogBox(message);
        dialogBox.avatar.setText("YOU");
        dialogBox.avatar.getStyleClass().add("user-avatar");
        dialogBox.dialog.getStyleClass().add("user-bubble");
        dialogBox.flip();
        return dialogBox;
    }

    /**
     * Creates a left-aligned dialog for a Quackie response.
     *
     * @param message response generated by Quackie
     * @return Quackie dialog box
     */
    public static DialogBox getQuackieDialog(String message) {
        DialogBox dialogBox = new DialogBox(message);
        dialogBox.avatar.setText("Q");
        dialogBox.avatar.getStyleClass().add("quackie-avatar");
        dialogBox.dialog.getStyleClass().add("quackie-bubble");
        return dialogBox;
    }

    /**
     * Places the user's avatar on the right of the message.
     */
    private void flip() {
        ObservableList<Node> children = FXCollections.observableArrayList(getChildren());
        Collections.reverse(children);
        getChildren().setAll(children);
        setAlignment(Pos.TOP_RIGHT);
    }
}
