package quackie;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.PrintStream;
import java.nio.charset.StandardCharsets;
import java.util.Scanner;
import java.util.StringJoiner;

import quackie.command.Command;
import quackie.parser.Parser;
import quackie.storage.Storage;
import quackie.task.TaskList;
import quackie.ui.Ui;

/**
 * Entry point for the Quackie chatbot.
 */
public class Quackie {
    private final Parser parser;
    private final Storage storage;
    private final TaskList tasks;

    /** Creates a chatbot backed by the default task storage file. */
    public Quackie() {
        this(new Storage());
    }

    /**
     * Creates a chatbot backed by caller-supplied storage.
     *
     * @param storage storage service used to load and save tasks
     */
    public Quackie(Storage storage) {
        this.parser = new Parser();
        this.storage = storage;
        this.tasks = loadTasks(storage, createDiscardingUi());
    }

    /**
     * Starts an interactive Quackie session.
     *
     * @param args command-line arguments, which are currently unused
     */
    public static void main(String[] args) {
        Ui ui = new Ui();
        ui.showWelcome();
        TaskList tasks;
        Storage storage = new Storage();
        Parser parser = new Parser();
        tasks = loadTasks(storage, ui);

        while (true) {
            String command = ui.readCommand();
            if (command == null) {
                return;
            }
            ui.showLine();

            if (command.isBlank()) {
                ui.showError("Please enter a command.");
            } else {
                try {
                    Command parsedCommand = parser.parse(command, tasks);
                    parsedCommand.execute(tasks, ui, storage);
                    if (parsedCommand.isExit()) {
                        return;
                    }
                } catch (IllegalArgumentException exception) {
                    ui.showError(exception.getMessage());
                }
            }

            ui.showLine();
        }
    }

    /**
     * Executes one command and returns its response for display in the GUI.
     *
     * @param command complete command entered by the user
     * @return response generated by the command
     */
    public String getResponse(String command) {
        ByteArrayOutputStream capturedOutput = new ByteArrayOutputStream();
        Ui ui = new Ui(new Scanner(""), new PrintStream(capturedOutput, true, StandardCharsets.UTF_8));

        if (command == null || command.isBlank()) {
            ui.showError("Please enter a command.");
        } else {
            try {
                Command parsedCommand = parser.parse(command, tasks);
                parsedCommand.execute(tasks, ui, storage);
            } catch (IllegalArgumentException exception) {
                ui.showError(exception.getMessage());
            }
        }

        return formatGuiResponse(capturedOutput.toString(StandardCharsets.UTF_8));
    }

    /**
     * Checks whether a command should end the GUI session.
     *
     * @param command complete command entered by the user
     * @return {@code true} when the command is {@code bye}
     */
    public boolean isExitCommand(String command) {
        return parser.parseCommandType(command) == CommandType.BYE;
    }

    /**
     * Loads saved tasks while keeping the chatbot usable when the data is invalid.
     *
     * @param storage the storage service to read from
     * @param ui the user interface used to report load failures
     * @return the loaded task list, or an empty list when loading fails
     */
    private static TaskList loadTasks(Storage storage, Ui ui) {
        TaskList tasks = new TaskList();
        try {
            storage.load(tasks);
            return tasks;
        } catch (IOException | RuntimeException exception) {
            ui.showError("I couldn't load saved tasks. Starting with an empty list.");
            return new TaskList();
        }
    }

    /**
     * Creates a UI that silently absorbs startup messages.
     *
     * @return a UI whose output is held only in memory
     */
    private static Ui createDiscardingUi() {
        ByteArrayOutputStream discardedOutput = new ByteArrayOutputStream();
        PrintStream output = new PrintStream(discardedOutput, true, StandardCharsets.UTF_8);
        return new Ui(new Scanner(""), output);
    }

    /**
     * Removes console-only separators and indentation from a captured response.
     *
     * @param capturedOutput response written by the console UI
     * @return response formatted for a chat bubble
     */
    private static String formatGuiResponse(String capturedOutput) {
        StringJoiner response = new StringJoiner(System.lineSeparator());
        capturedOutput.lines()
                .filter(line -> !line.matches("_+"))
                .map(String::stripLeading)
                .forEach(response::add);
        return response.toString().strip();
    }

}
